### ISSUE TITLE
Is there any particular reason why you choose to go with Apache over Nginx?

### ISSUE THREAD

**Issue by PauloPhagula** [nexcess/magento-whitepaper-april-2018#1]
In the community, Nginx is usually considered more performant in comparison to Apache, for serving static files, handling massive numbers of connections, like most Magento sites call for, specially when used with PHP-FPM. Given that, is there any particular reason why you choose to go with Apache over Nginx?

Thanks

**Comment by jaywilliams** [comment]
I can't speak for Nexcess personally, but I find Apache is often used in customer hosting environments due to the familiarity and application support for Apache (e.g. .htaccess files). All programs work out of the box with Apache, not so with Nginx.

That being said, Nginx has vastly better performance, and that's what I use, but then again, I'm hand-tweaking the server configs myself.

**Comment by ChrisOrlando** [comment]
Two main points:
- As @jaywilliams described, many customers and applications expect apache and they expect .htaccess to work. We use it on our servers. We also use nginx in front of Apache in some cases to serve static assets and cache things, which gives some performance advantages while still allowing .htaccess to work.
- Apache + php-fpm is a lot closer in performance to nginx + php-fpm than it is to Apache + mod_php or some other setup.

**Comment by PauloPhagula** [comment]
Thank you for your replies
